<?php

namespace Tests\Feature;

use Tests\TestCase;
use App\Models\User;
use Illuminate\Http\Request;
use App\Services\UserService;
use Illuminate\Support\Facades\Hash;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;

class LoginFunctionIsWorkingTest extends TestCase
{
   use RefreshDatabase;
    
    private $userService;
    

    protected function setUp(): void
    {
        parent::setUp();

        $this->userService = app(UserService::class);
    }
    /**
     * Ensure that the login function properly authenticates users with valid credentials.
     */
    public function test_login_function_authenticates_valid_users(): void
    {  
        $user = User::factory()->create([
            'email' => 'peter@gmail.com',
            'password' => bcrypt('password'),
            'user_type'=>'student',
        ]);
    
        $response = $this->get(route('login')); // GET request creates session & CSRF
    
        $token = session('_token'); // fetch CSRF token generated by Laravel
    
        $response = $this->post(route('login'), [
            'email' => 'peter@gmail.com',
            'password' => 'password',
            '_token' => $token,       // ✅ include CSRF token
        ]);
     
        dump(auth()->check());
        dump($response);
        $response->assertRedirect(route('dashboard'));
        $this->assertAuthenticatedAs($user);
    
    } 

}//endof class
