<?php

namespace Tests\Feature;

use App\Models\User;
use App\Services\UserService;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Tests\TestCase;

class LoginFunctionIsWorkingTest extends TestCase
{
    use RefreshDatabase;

    private $userService;

    protected function setUp(): void
    {
        parent::setUp();

        $this->userService = app(UserService::class);
    }

    /**
     * Ensure that the login function properly authenticates users with valid credentials.
     */
    public function test_login_function_authenticates_valid_users(): void
    {
        $user = User::factory()->create([
            'email' => 'peter@gmail.com',
            'password' => bcrypt('password'),
            'user_type' => 'student',
        ]);

        $response = $this->get(route('login'));  // GET request creates session & CSRF

        $token = session('_token');  // fetch CSRF token generated by Laravel

        $response = $this->post(route('login'), [
            'email' => 'peter@gmail.com',
            'password' => 'password',
            '_token' => $token,  // ✅ include CSRF token
        ]);

     
        $response->assertRedirect(route('dashboard'));
        $this->assertAuthenticatedAs($user);
    }//endof fucntion 

    public function test_login_function_do_not_authenticate_invalid_users(): void
    {
        $user = User::factory()->create([
            'email' => 'peter@gmail.com',
            'password' => bcrypt('password'),
            'user_type' => 'student',
        ]);

        $response = $this->get(route('login'));  // GET request creates session & CSRF

        $token = session('_token');  // fetch CSRF token generated by Laravel

        $response = $this->post(route('login'), [
            'email' => 'allan@gmail.com',
            'password' => 'password123',
            '_token' => $token,  // ✅ include CSRF token
        ]);

        #returns back with errors
        $response->assertSessionHasErrors(['email']);
        #no one is authenticated
        $this->assertGuest();
    }//endof fucntion 

    


}  // endof class
